### ISSUE TITLE
Llama slots

### ISSUE THREAD

**Issue by BoostAteHisDog** [catppuccin/minecraft#29] opened 2023-10-11 22:32 UTC
<img width="71" alt="image" src="https://github.com/catppuccin/minecraft/assets/81974118/03aec426-0329-40b1-9dac-074033147734">
As you can see here, there are 3 slots for the llama. But if I take catppuccin off, this is what it looks like.
<img width="91" alt="image" src="https://github.com/catppuccin/minecraft/assets/81974118/e5289266-de58-4283-9e94-9109cad835f0">
The llama should only have one slot.

**Comment by JustLetterV** [comment] 2023-10-14 23:31
There isn't a perfect fix for this. The issue is that Llamas, Horses and Mules all use the same gui texture. There are few options how this can be done:
1. How it looks right now. 3 (or 2, since the bottom one could be removed entirely) slots show up always no matter how many can be used.
2. Slots have thinner borders, but only slots that can be used show up.
![image](https://github.com/catppuccin/minecraft/assets/75657829/4ea4dbea-e4b0-40fd-a43e-0f9b522e660f) 
![image](https://github.com/catppuccin/minecraft/assets/75657829/9ad00430-3bf4-409b-92db-03f14e3cb1da)
3. Change the slot background color to the same as the slot border. After this correct amount of slots would show up and it would also look good. The only downside is that the Llama carpet slot would have a thicker border on one side.
![image](https://github.com/catppuccin/minecraft/assets/75657829/3c65c165-a179-489c-a952-446b3cf66178) 
![image](https://github.com/catppuccin/minecraft/assets/75657829/8a99ead7-3f07-4d47-b7b3-3e9678bdd1fa)

Initially, I just decided to go with option 1 since it looks good and slots that can be used have icon of the item that can be put into the slot. The third option would solve the issue and look good, but which option do you think would be the best?

**Comment by BoostAteHisDog** [comment] 2023-10-15 01:38
I think the 3rd one would look the best.

**Comment by JustLetterV** [comment] 2023-11-10 13:24
Fixed in the newest version now available on Modrinth

**Closed as completed by JustLetterV** 2023-11-10 13:24 UTC
